### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by adrienpicard** [confluxgroup/craft-level-entry-types#9]
Would be great to know if the plugin works with Craft 4, or if you plan to support the new version in the future. Thank you!

**Comment by dreadfullyposh** [comment]
We haven't done any testing yet for Craft 4. It's looking like some of the new features in Craft 4 may remove the need for this plugin altogether. We'll definitely be taking a closer look to determine if it's worth continuing to develop Level Entry Types or not.

**Comment by stuible** [comment]
I don't believe that Craft 4 implements the very useful functionality found in this plugin.  I would also very much appreciate Craft 4 compatibility as it would allow me to upgrade to Craft 4 and extend the lifespan that my website is able to receive Craft updates.

**Comment by jacobgraf** [comment]
Any updates on this one? Just trying to determine if I should uninstall this plugin in the meantime so I can upgrade to Craft 4 or if an updates is imminent? I also didn't see any native functionality that would take the place of this plugin and it definitely provides functionality that helps keep our editors from messing something up. :-)

**Comment by dreadfullyposh** [comment]
Hi all,

Thanks for following up. At the moment we don't have a Craft 4 version ready, but we have done some initial testing and should be able to get it working. I don't have an ETA yet, but hopefully we can get it out soon since it should only take some minor adjustments.

**Comment by stuible** [comment]
Just checking in with this issue, have you made any progress towards a Craft 4 compatible release?

**Comment by kylecotter** [comment]
We’ve made some progress on a Craft 4 version but have hit a few roadblocks along the way due to some of the changes with the markup available in the CP.

We’re still exploring our options as bringing this plugin to Craft 4 is still something we’d like to do, but it’s not our highest priority at the moment.

Thanks for understanding.

**Comment by stuible** [comment]
Thank you for the response.  Would you be willing to extend our craft plugin licence to encompass this new update when it is available?  We purchased a license with the understanding that we would be receiving updates for a year after purchase.

**Comment by dreadfullyposh** [comment]
We don't have any control over licenses after they are issued by the Craft plugin store. I'd be happy to issue you a new perpetual license if you provide the original email address and date of purchase via email to me at hello@confluxgroup.com

That said, at this point we are not planning to release a Craft 4 compatible version at this point, since Craft 4 functionality and the functionality P&T has indicated is coming in future versions largely makes this plugin unnecessary.
